akka.http.cors {
  allowed-origins = ["*"]
  allowed-headers = ["Content-Type", "Authorization"]
}

akka.javasdk.agent {
  model-provider = openai
  openai {
    base-url = "https://api.groq.com/openai/v1"
    model-name = "llama-3.1-8b-instant"
  }
}
